# Generated by Django 5.0.6 on 2024-07-08 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invista_me', '0002_investimento_nivwl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investimento',
            name='nivwl',
        ),
    ]
